//
// DeleteServiceTokens.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteServiceTokens: Codable, JSONEncodable, Hashable {

    public var eduId: String?
    public var tokens: [TokenRepresentation]?

    public init(eduId: String? = nil, tokens: [TokenRepresentation]? = nil) {
        self.eduId = eduId
        self.tokens = tokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eduId
        case tokens
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(eduId, forKey: .eduId)
        try container.encodeIfPresent(tokens, forKey: .tokens)
    }
}

